---
title: "MS_2"
author: "Paddy Adams"
date: "14/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Commentary on two previous projects:


1. Robert McKenzie: NYC Taxi Pickup and Dropoff VIsualization

This is the project my freshman roomate put togther so I witnessed the process of putting it together. T the time I had no idea what he was really doing but looking at it now I find it failry impressive. There is a lot of raw data involved. A few cons would that it seems fairly hard to get the page to work and display the data with filters applied. It also displays complicated numbers without explaining their meanings. However once it is working it very neatly shows the busiest areas, best spots for tipping etc... As such if you were a taxi driver it would be increadibly useful to know so that you could optimise your earnings. 

2. Pieter Quinton: Housing Market. An examination of the housing market, starting at the national level and narrowing the scope all the way to just one city.

I chose this project because it is Pieter's birthday and I remember he took this course. Pieter's project, although being on a rather dry topic, shows the given data very clearly and with good aesthetics. He also provides very good explainatons as to what is going on, and also as to why he is has done it. The trends shown by the graphs are also explained well. I don't know how much data cleaning was requried for the project, but I think it would have been more than Robert's project.  

